# Generated by Django 5.2 on 2025-05-15 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=400, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=400, null=True, verbose_name='Subtitulo')),
                ('descripcion', models.TextField(max_length=2000, verbose_name='Descripcion')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('numero_likes', models.IntegerField(default=0, verbose_name='Numero likes')),
                ('numero_dislikes', models.IntegerField(default=0, verbose_name='Numero dislikes')),
                ('numero_mejora', models.IntegerField(default=0, verbose_name='Numero mejoras')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.area')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.categoria')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo_contenido', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video'), ('code', 'Código'), ('link', 'Enlace')], max_length=20)),
                ('contenido_bloque', models.TextField()),
                ('posicion', models.IntegerField()),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.recurso')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenidos',
            },
        ),
    ]
