# Generated by Django 5.2 on 2025-05-15 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='recurso_id',
            new_name='recurso',
        ),
    ]
