# Generated by Django 5.2 on 2025-05-27 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_rename_recurso_id_contenido_recurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo_voto', models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta'), ('mejora', 'Necesita mejora')], max_length=10, verbose_name='Tipo de voto')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.recurso', verbose_name='Recurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto de Recurso',
                'verbose_name_plural': 'Votos de Recursos',
                'db_table': 'votos_recursos',
                'unique_together': {('usuario', 'recurso')},
            },
        ),
    ]
